name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            autopoint \
            libtool \
            libltdl-dev \
            libffi-dev \
            pkg-config \
            cmake \
            libssl-dev \
            zlib1g-dev \
            openjdk-17-jdk

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer
          python -m pip install "cython==0.29.37"

      - name: Clean Buildozer
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZP-Polytechnic-APK
          path: bin/*.apk
