name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip lld build-essential libffi-dev libssl-dev autoconf libtool pkg-config openjdk-17-jdk git cmake
        pip install "cython<3.0.0" "buildozer==1.5.0" "python-for-android==2024.1.21"

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZP_Schedule_App
        path: bin/*.apk
